app:
  name: user-flow
  environment: dev
  url: 0.0.0.0:8000

db:
  postgres:
    connection: postgres
    host: 192.168.0.103
    port: 5439
    database: user-flow
    username: rustem
    password: rustem-admin
    sslmode: disable